# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$package\
$dart\
$golang\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$php\
$python\
$ruby\
$rust\
$swift\
$terraform\
$conda\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# This prompt is rendered instead of the normal prompt when the user has
# entered an incomplete statement (such as a single left parenthesis or quote).
# continuation_prompt = "▶▶"

[directory]
style = "bold blue"
truncation_length=5

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[took](bold bright-white) [$duration]($style)"
style = "bold yellow"
show_milliseconds=false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 20
style = "bold yellow"